### ISSUE TITLE
LogViewerControl NullReferenceException

### ISSUE THREAD

**Issue by DarkDaskin** [WildGums/Orc.Controls#10]
A `NullReferenceException` occurs at [LogViewerControl.xaml.cs#L248](https://github.com/WildGums/Orc.Controls/blob/develop/src/Orc.Controls/Orc.Controls.Shared/Controls/LogViewer/Views/LogViewerControl.xaml.cs#L248) at application startup. This happens because `OnViewModelLogMessage` can be called before `UpdateControl` if no control properties are changed from the default values.

**Comment by mkhomutov** [comment]
agree, the `UpdateControl` method should be used before the `OnViewModelLogMessage`
and 'UpdateControl' method used each time when you're changing any property of the `LogViewerControl`
but `OnViewModelLogMessage` can be called only when ViewModel has been created. And LogListenerType should be defined as well.
And if we have initialized value in 'LogListenerType', then `UpdateControl` should be already called.

So, theoretically `OnViewModelLogMessage` can't be called before the `UpdateControl`

If I'm wrong, just describe your scenario. And always feel free to make pull request with bug fixes.

**Comment by GeertvanHorrik** [comment]
So the fix is easy, just check for null. If so, return. @DarkDaskin, interested in creating a PR?

**Comment by GeertvanHorrik** [comment]
Fixed.
