### ISSUE TITLE
Side effects of styles defined for DateTimePicker and DatePicker

### ISSUE THREAD

**Issue by jdehaan** [WildGums/Orc.Controls#12]
### Steps to reproduce

1. Define a togglebutton and/or a ListBox with items for a WPF application
2. Reference Orc.Controls
3. Also bind the Orc.Controls default generic theme

Platform:
.NET version: 4.0

### Expected behaviour

The theme for Orc.Control DateTimePicker and DatePicker shall not impact on default controls (non Orc.Controls)

### Actual behaviour

The togglebutton or listboxitem default styles are impacted in a negative way (become invisible)

### Additional information

By inlining the default theme from Orc.Controls and commenting out following resource dictionary references:
`       
`
 
Then bad behaviour disappears. So these xaml are not boxed.

The Behaviour was ok in version 1.2.0, version 1.3.0 introduced the bad behaviour reported here (tested)

**Comment by mkhomutov** [comment]
@ceo1647, please look into this issue

**Comment by mkhomutov** [comment]
but if this is urgent for you, @jdehaan , then you can try to fix it by yourself and make pull request

**Comment by jdehaan** [comment]
It's not so urgent we stick to the old version at the moment. Unfortunately I am not an expert for styling issues. I struggle and fight all the time and just stick to defaults. I enjoy WPF for MVVM more than for the ability to theme and style (in the end to me ability to style is of no importance) But here the is a functional impact of styles. I am not sure how to fix it.

I had however a look in the code and I suspect the culprit is the removal of the lines

`<Style TargetType="{x:Type local:DatePickerControl}">
        <Style.Resources>
`

This "scoped" nicely everything. Due to the change for 1.3.0 and the scope removal IMHO the styles coming below apply globally. The ControlTemplate has a key but many styles below do not and thus AFAIK apply directly always to the TargetType.

But unfortunately I cannot judge what would be a clean fix for this issue...

**Comment by GeertvanHorrik** [comment]
We should never set default styles without an explicit key. We probably added a default margin to the types, not with the actual key so need to look into this.

**Comment by ceo1647** [comment]
Yes. Some default styles are applied globaly now. This is not good, thanks @jdehaan for indicating a bug. Will fix it soon

**Comment by mkhomutov** [comment]
@jdehaan, we have released Orc.Controls v1.3.5-beta12
it is working good for us. Could you please check if we have fixed the issue?

**Comment by jdehaan** [comment]
Good job! I could not observe the negative effects anymore after updating to the mentioned version.
