### ISSUE TITLE
PropertyChanged not fired on OpenFilePickerView

### ISSUE THREAD

**Issue by vicgerrard** [WildGums/Orc.Controls#13]
I have this code:
```
public class Settings : SavableModelBase<Settings>
{
 //fody properties
 public string AccountsPath {get; set;}
 [ExcludeFromSerialization]
 public string[] Accounts {get; set;}
 protected override void OnPropertyChanged(AdvancedPropertyChangedEventArgs e)
 {
      switch (e.PropertyName)
            {
                case nameof(AccountsPath):
                    LoadAccounts();
                    break;
            }
            base.OnPropertyChanged(e);
 }
private void LoadAccounts()
        {
            if (!File.Exists(AccountsPath)) return;
            Accounts = File.ReadAllLines(AccountsPath);
        }
}
```

And I have settings datawindow with OpenFilePickerView binded to Settings.AccountsPath.
When user choosed file property changed firing, but if user choosed same file again (edited in notepad, for example) property changed not firing. Can i fix that or i should manually update file if it is edited?

**Comment by GeertvanHorrik** [comment]
I'm very sorry for the late reply, completely missed this issue. The property will only be updated if it really reflects a different value. We could change this in the command though (if values are equal, force a property change). Interested in doing a PR?

**Comment by GeertvanHorrik** [comment]
Assigning to @michu , please always raise a property changed when explicitly invoking the command.

**Comment by michu** [comment]
Fixed in https://github.com/WildGums/Orc.Controls/commit/64668a56f09ca265f89ba1977e2c04e8aea61875

**Comment by GeertvanHorrik** [comment]
Well done, thanks!
