### ISSUE TITLE
Because styles have no Key assigned, it's not possible to use them in BasedOn field for custom styles

### ISSUE THREAD

**Issue by mvacha** [WildGums/Orc.Controls#17]
### Feature description
Discovered this when using [TimeSpanControl](https://github.com/WildGums/Orc.Controls/tree/ca322765d08869bc96945484684f1787fd84c060/src/Orc.Controls/Orc.Controls.Shared/Controls/TimeSpan)
`<Style ... BasedOn="{StaticResource {x:Type orc:TimeSpanControl}}">` wont work because x:keys are not set for default styles.

Inside WPF default styles the keys are set like this:
``` 
<Style x:Key="{x:Type TextBox}"
           BasedOn="{StaticResource {x:Type TextBoxBase}}"
           TargetType="{x:Type TextBox}">
</Style>
```
So the mentioned code would work for them. I think this project should follow this convention.

**Comment by GeertvanHorrik** [comment]
I think you're making a good point here. Are you interested in contributing by creating a PR for this?

**Comment by mvacha** [comment]
@GeertvanHorrik Sure thing, should I name the branch something like "base-style-names"?

**Comment by GeertvanHorrik** [comment]
For pr's, it doesn't really matter (since they are all done against the *develop* branch of this repository).

**Comment by GeertvanHorrik** [comment]
PR accepted.

**Comment by GeertvanHorrik** [comment]
Build - 1.5.0-unstable.11 is available on NuGet.
