### ISSUE TITLE
Range slider is not displaying correctly

### ISSUE THREAD

**Issue by GeertvanHorrik** [WildGums/Orc.Controls#190]
Color range seems to have a wrong offset.

**Comment by Averus-a** [comment]
![image](https://user-images.githubusercontent.com/14249631/81164125-e489d900-8fa0-11ea-9de8-c512c963dcbd.png)
How is RangeSlider's TrackBackground placed right now

**Comment by ceo1647** [comment]
![image](https://user-images.githubusercontent.com/5163834/81375388-7402c980-9112-11ea-8a36-33f6875bd14a.png)

**Comment by GeertvanHorrik** [comment]
@ceo1647 , isn't the vertical displaying incorrectly now?

**Comment by ceo1647** [comment]
it still incorrect...
