### ISSUE TITLE
Style Expander so it uses theming capabilities from Orc.Theming

### ISSUE THREAD

**Issue by GeertvanHorrik** [WildGums/Orc.Controls#196]

**Comment by ceo1647** [comment]
this issue blocked by #217

**Comment by ceo1647** [comment]
![image](https://user-images.githubusercontent.com/5163834/82311480-d2fbf480-99d6-11ea-9b1b-982a3770812b.png)
we have now fully functional expander with configurable Collapse/Expand duration, that respects Orc.Theming library
