### ISSUE TITLE
Design of Pickercontrols

### ISSUE THREAD

**Issue by jensweller** [WildGums/Orc.Controls#2]
![asitis](https://cloud.githubusercontent.com/assets/7700913/11295689/7fe22a4e-8f6d-11e5-9f3a-657dcfbc2952.png)
![asitshouldbe](https://cloud.githubusercontent.com/assets/7700913/11295690/7fe48d84-8f6d-11e5-9ec7-41d8f316a17e.png)

As you see in the screenshots: 
No space between the textbox and the buttons. 
Textbox is higher then the buttons

**Comment by GeertvanHorrik** [comment]
It looks like you are using custom styles for the TextBox control. Is it something that happens on empty projects or in your project specifically?

**Comment by jensweller** [comment]
Hi. Yes this is a example form a empty project.

**Comment by GeertvanHorrik** [comment]
Can you please attach the repro here?

**Comment by jensweller** [comment]
For sure but how. I can only upload folowing file types here.
 PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF

**Comment by GeertvanHorrik** [comment]
Not zip files? That's not good... Can you do a dropbox / OneDrive upload for now?

**Comment by jensweller** [comment]
No Zip files. Also tried to rename the file ending. Then the system closed my issue. No tricks allowed :-)
Sorry but its not possible for me to upload something elsewere.
I know you have lots of work but I think in this case its much easier to add only this lines in a new wpf project.

<StackPanel>
      <orc:SaveFilePickerView />
</StackPanel>

Thats the only thing I do.

**Comment by jensweller** [comment]
?! I do not see my inserted xaml code. !?
orc:SaveFilePickerView in a Stackpanel  thats the only think

**Comment by TanyaPristupova** [comment]
Hi jensweller. Please take a look at Orc.Controls.Examples project.
There are styles defined in resources in SaveFilePickerView.xaml. Following style changes the height of text box:
<Style TargetType="{x:Type TextBox}">
            <Setter Property="Margin" Value="6"/>
</Style>
You need to add this style to your resources.

**Comment by jensweller** [comment]
Realy? I have to set a style if I want to use the default behavior?

**Comment by GeertvanHorrik** [comment]
We were talking about improving it for you, but the response isn't really motivating.

**Comment by jensweller** [comment]
Sorry. Yes you are right. Thanks for fixing.

**Comment by jensweller** [comment]
But maybe its motivating that I am the first one who asks a question about this control :-)

**Comment by GeertvanHorrik** [comment]
We provide these libraries to the outside world for free, but we are primary customers (or users). Our own requirements decide what features get done when. It's nice to hear that others see the components as useful, but we don't achieve anything by people just using the components.

One way you could contribute is to do PR / blog / etc. There are tons of (non-money spending) ways to contribute to open source, that is truly motivating to us. Just remember that whenever you are commenting on a free open source project, people are doing a *lot of work for free*. If you reach out to them with that in mind, you might get more done in the future. In the end it's partly why you get paid your salary.

**Comment by jensweller** [comment]
Hi. For sure. But I do not just use them. I reported a bug. Its a small one ok, but thats also contribution.
Ok the last sentence was not helpfull sorry.
