### ISSUE TITLE
FilterBox Control does not display

### ISSUE THREAD

**Issue by fmongeau** [WildGums/Orc.Controls#22]
I've documented an issue I have with the FilterBox control in the attached pdf (with screen shots). This, I think, explains succinctly the issue. It's a very quick read. The orc:FilterBoxControl simply does not show, neither in design mode nor in debug mode.
This may be a newbie problem. I appreciate any help. Thank you kindly.
[Issue FilterBoxControl.pdf](https://github.com/WildGums/Orc.Controls/files/987866/Issue.FilterBoxControl.pdf)

**Comment by GeertvanHorrik** [comment]
Thanks for the detailed info. You should probably include the theme in your app.xaml:

```

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Orc.Controls;component/Themes/Generic.xaml" />            </ResourceDictionary.MergedDictionaries>

            <SolidColorBrush x:Key="AccentColorBrush" Color="Orange" />
        </ResourceDictionary>
    </Application.Resources>
```
