### ISSUE TITLE
Use Microsoft.Xaml.Behaviors.Wpf instead the System.Windows.Interactivity

### ISSUE THREAD

**Issue by okunevdm** [WildGums/Orc.Controls#250]
Catel v5.12.6 uses Microsoft.Xaml.Behaviors.Wpf for all services.
Orc.Controls.DropDownButton v3.4.1 still uses System.Windows.Interactivity.
Please fix it.

**Comment by GeertvanHorrik** [comment]
The pre-release are all fixed, but we are finalizing Orc.theming before releasing a new stable version.

**Comment by GeertvanHorrik** [comment]
Closing this ticket since we are actively working on it and have a pre-release ready for testing.
