### ISSUE TITLE
NumericTextBox up and down keys

### ISSUE THREAD

**Issue by michu** [WildGums/Orc.Controls#3]
Hi,

Look at this code:

`
if (e.Key == Key.Up && AllTextSelected) {
                OnUpDown(1);
                e.Handled = true;
            }
            if (e.Key == Key.Down)
            {
                OnUpDown(-1);
                e.Handled = true;
            }`

This is found in NumericTextBox::OnPreviewKeyDown(KeyEventArgs e) method.
Is it ok that only up key checks whether all text is selected and down key is not checking ?
I can fix it if you wish.

**Comment by Orcomp** [comment]
Yes please fix this. Thanks.

**Comment by michu** [comment]
Fixed in 9358e77 commit.
