### ISSUE TITLE
Install Nuget Package error

### ISSUE THREAD

**Issue by heronrobledo** [WildGums/Orc.Controls#502]
Severity Code Description Project File Line Suppression Status
Error Unable to install package 'Orc.Controls 4.8.0'. You are trying to install this package in a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that support this framework. For more information, contact the package author.

**Comment by GeertvanHorrik** [comment]
Orc.Controls does not support .NET Framework 4.0. And vNext will *only* support .NET 6
