### ISSUE TITLE
[Feature]: MultiSelect ComboBox 

### ISSUE THREAD

**Issue by vaecors** [WildGums/Orc.Controls#70]
### Purpose

To introduce a new control to Orc's Control Ecosystem called a MultiSelect ComboBox. As shown below it can be either one of these variations (or both).

![CheckedDropDownMock](https://user-images.githubusercontent.com/49293119/57050803-5885f880-6c4c-11e9-8eed-a27ec6d816ec.png)

### Feature description

The premise of this feature is to introduce the supported concept of multiple item selection to a ComboBox. This would allow the implementer to leverage support for multi-value collections (such as a collection of strings, integers and so forth) in an easy to use form. 

At a high-level the API for the control would have the following exposed properties:

| Property Name  | Property Type | Binding Mode |
| ------------- | ------------- | ------------- |
| ItemsSource  | IEnumerable  | Two-Way |
| SelectedItems | IEnumerable | Two-Way |
| DisplayMemberPath | string | One-Way to Source |
| SelectedValueMemberPath | string | One Way to Source |

`DisplayMemberPath` and `SelectedValueMemberPath` are leveraged properties for when the underlying `ItemsSource` type is of either `IDictionary<TKey, TValue>` or `IEnumerable<KeyValuePair<TKey, TValue>>` or a collection composing of business objects rather than primitive types.

### Conjecture

If `DisplayMemberPath` is not defined then the `ToString()` method of the underlying type is called.

If `SelectValueMemberPath` is not defined, then the underlying type is used.

### Final Notes

This is all preliminary and it is possible that feature development may be accelerated using some of the foundation of the [ColorLegend](http://opensource.wildgums.com/orc.controls/colorlegend/) control. I am willing to take ownership of this feature development once my time allows. The request for the feature is not due to a needed business requirement but rather a desire to contribute to the library.

**Comment by GeertvanHorrik** [comment]
Sounds like a great control to have. The mock-ups show it as a window, but I think we can implement this as a separate control (without the buttons) so it can be used anywhere? 

Pinging @ceo1647 / @mkhomutov , in case you are interested in helping out with the development as well.

**Comment by vaecors** [comment]
My apologies if the mock ups make it seem like it’s a window. It is actually not a window. The button row is part of the listbox drop down. The design is intentional to prevent closure of the dropdown upon checking an item or moving off focus.
