### ISSUE TITLE
Incorrect ElementName in XAML Binding at TimeSpanPicker control

### ISSUE THREAD

**Issue by mindball** [WildGums/Orc.Controls#730]
The XAML code provided has a Border element with a Visibility property that is bound to the IsVisible property of an element named PART_NumericTBEditorContainer. However, the error message suggests that the ElementName should be PART_NumericTBEditorContainerBorder. To resolve this issue, you should change the ElementName in the Visibility binding of the Border element from PART_NumericTBEditorContainer to PART_NumericTBEditorContainerBorder. Here’s the corrected code:

```
<ControlTemplate` TargetType="{x:Type controls:TimeSpanPicker}">
    <Grid VerticalAlignment="Stretch">
        <Border x:Name="PART_MainContainer"
        Margin="0"
        Padding="{TemplateBinding Padding}"
        BorderThickness="1" 
        Visibility="{Binding ElementName=PART_NumericTBEditorContainerBorder, Path=IsVisible, Converter={catel:BooleanToCollapsingVisibilityConverter SupportInversionUsingCommandParameter=True}, ConverterParameter=True}"
        Style="{DynamicResource TimeSpanBorderStyle}">
    </Grid>
</ControlTemplate>
```

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, releasing hotfix 5.0.1
