### ISSUE TITLE
DateTimeFormatInfoExtensions.SetMonthFormat doesn't accept MMM which is a valid month modifier

### ISSUE THREAD

**Issue by bigworld12** [WildGums/Orc.Controls#91]
if my system's short date format defines month as `MMM` (which is a valid month format) 
![image](https://user-images.githubusercontent.com/10135395/60383266-01937880-9a6f-11e9-9158-3dfe833d12db.png)
![image](https://user-images.githubusercontent.com/10135395/60383303-60f18880-9a6f-11e9-92db-3c40f61e4f22.png)

`DateTimeFormatInfoExtensions.SetMonthFormat` fails since it hard-checks if the month format length is > 2 and raises an exception
ref : https://github.com/WildGums/Orc.Controls/blob/develop/src/Orc.Controls/Extensions/DateTimeFormatInfoExtensions.cs#L138

it's also worthy to note that MMMM is also a valid month modifier

suggested solution would be to increase the limit to length > 4 instead of 2

list of some valid DateTime formats : https://www.c-sharpcorner.com/blogs/date-and-time-format-in-c-sharp-programming1

**Comment by GeertvanHorrik** [comment]
This is put on the list for today.

**Comment by GeertvanHorrik** [comment]
Added unit tests and written fix.

**Comment by GeertvanHorrik** [comment]
Hotfix Build - 3.2.11 being released right now. I will close this ticket, but let me know if any issues arise.

Thanks for reporting!
